name = "MakiePublication"
uuid = "dde8697e-0d61-460d-88dd-856f66710dd1"
authors = ["Yi-Xin Liu <lyx@fudan.edu.cn>"]
version = "0.3.2"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"

[compat]
ColorSchemes = "3.14"
Colors = "0.12"
Makie = "0.18, 0.19"
julia = "1.6"
